import { test, expect } from '@playwright/test';

test.describe('1on1 Session Flow', () => {
  
  test.beforeEach(async ({ page }) => {
    // Navigate to dashboard
    await page.goto('/');
  });

  test('User can start a session, see transcript, and end it with summary', async ({ page }) => {
    // 1. Check Dashboard
    await expect(page).toHaveTitle(/Memento 1on1/);
    await expect(page.getByText('Start 1on1')).toBeVisible();

    // 2. Start Session Modal
    await page.getByText('Start 1on1').click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByText('Start New 1on1 Session')).toBeVisible();

    // Fill form
    // Antd Select is a bit tricky, often needs to click the trigger
    const subSelect = page.locator('#subordinateId'); // Antd puts id on input
    await subSelect.click();
    // Select first option
    await page.locator('.ant-select-item-option').first().click();

    // Type Theme
    await page.fill('#theme', 'Playwright Test Theme');

    // Click OK (Start Session)
    await page.getByText('Start Session', { exact: true }).click();

    // 3. Verify Session Page URL (UUID format)
    await expect(page).toHaveURL(/\/session\/[0-9a-f-]+/);
    await page.waitForLoadState('networkidle');
    
    // 4. Wait for session data to load
    // The page shows "Loading session data..." spinner while fetching
    await expect(page.getByText('Loading session data...')).toBeHidden({ timeout: 15000 });
    
    // Additional wait for data to be fully loaded
    await page.waitForTimeout(2000);
    
    // Check that session header is visible (indicates data loaded)
    await expect(page.getByText(/1on1 with/)).toBeVisible({ timeout: 10000 });
    
    // 5. Verify Real-time elements (Mock)
    // Wait for session page to load
    await expect(page.getByText('AI Copilot')).toBeVisible({ timeout: 15000 });
    await expect(page.getByText('Playwright Test Theme')).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('Live Transcript')).toBeVisible({ timeout: 10000 });
    
    // Check Controls
    await expect(page.getByRole('button', { name: 'End Session' })).toBeVisible();

    // 5. Test Mind Map Switching
    await page.getByRole('button', { name: 'Switch to MindMap' }).click();
    // Wait for mode switch and ensure MindMap mode UI is visible
    await expect(page.getByRole('button', { name: 'Switch to Video' })).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('Add Topic')).toBeVisible({ timeout: 10000 });
    
    // Add a manual node
    await page.getByText('Add Topic').click();
    await expect(page.getByText('New Topic')).toBeVisible({ timeout: 5000 });

    // Switch back
    await page.getByRole('button', { name: 'Switch to Video' }).click();

    // 6. End Session
    await page.getByRole('button', { name: 'End Session' }).click();

    // 7. Verify Summary Page
    await expect(page).toHaveURL(/\/session\/[0-9a-f-]+\/summary/);
    await expect(page.getByText('Session Completed Successfully')).toBeVisible();
    
    // Check for AI Summary
    await expect(page.getByText('AI Executive Summary')).toBeVisible();
    await expect(page.getByText('Automatic summary generated by AI')).toBeVisible();
    
    // Check for Transcript
    await expect(page.getByText('Full Transcript')).toBeVisible();
    await expect(page.getByText('Playwright Test Theme')).toBeVisible(); // Theme in details
  });

});
